#!/bin/sh

# =============================================================================
# Begin Global Config

ECHO=/bin/echo
ENV_SUBDIR=_environments
WP_ROOT=`pwd`

# End Global Config
# =============================================================================





# =============================================================================
# Begin Function Definitions

function ensure_cfg_is_run {
  if [ ! -f "wp-config.php" ]; then
    $ECHO "  [ERROR] Please complete initial Wordpress setup before running this script"
    exit
  fi 
}

function extract_cfg_var {
  grep "^define('$2'" $ENV_SUBDIR/$1-config.php | awk -F "'" '{print $4}'
}

function extract_db_vars {
  DB_NAME=`extract_cfg_var $1 DB_NAME`
  DB_HOST=`extract_cfg_var $1 DB_HOST`
  DB_USER=`extract_cfg_var $1 DB_USER`
  DB_PASS=`extract_cfg_var $1 DB_PASSWORD`
}

function hostname_for_env {
  grep "^DEPLOY_HOST" $ENV_SUBDIR/$1-hostname.php | awk -F "=" '{print $2}'
}

function dump {
  if [ -n "$DB_PASS" ]; then
    PW_ARG="-p$DB_PASS"
  else
    PW_ARG=""
  fi
  mysqldump -h $DB_HOST -u $DB_USER $PW_ARG $DB_NAME
}

# End Function Definitions
# =============================================================================





# =============================================================================
# Begin Script Execution

# Make sure we're executing in the right place
ensure_cfg_is_run

extract_db_vars $1

HOST1=$(hostname_for_env $1)
HOST2=$(hostname_for_env $2)

# BSD sed on macos doesn't have a case-insensitive flag, have to resort to perl :(
dump | perl -pe "s/$HOST1/$HOST2/gi"

# End Script Execution
# =============================================================================