#!/bin/bash


# =============================================================================
# Begin Global Config

ECHO=/bin/echo
ENV_SUBDIR=_environments
WP_ROOT=`pwd`

# End Global Config
# =============================================================================





# =============================================================================
# Begin Function Definitions

function ensure_git_is_clean {
  #If we have a git repo, and the working dir is dirty...
  if [ -d ".git" ]; then
    git status | grep clean 2>&1 > /dev/null
    if [[ $? != 0 ]]; then
      $ECHO "  [ERROR] All files must be committed to git before running this script"
      exit 1
    fi
  fi
}

function git_add_and_commit {
  $ECHO -n "  Saving progress..."
  git add -A > /dev/null
  git commit -m "$1" 2>&1 > /dev/null
  $ECHO "done."
}


# End Function Definitions
# =============================================================================






# =============================================================================
# Begin Script Execution

ensure_git_is_clean

$ECHO "Preparing CI Database..."
dt/dbmigrate development ci > _environments/ci_staged.sql
git_add_and_commit "Staging CI database $(date)"

$ECHO
$ECHO done\!
$ECHO
# End Script Execution
# =============================================================================